server:
  port: 8080


spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&useSSL=false
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver

#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true

#mybatis:
#  mapper-locations: classpath:mappers/*xml
#  type-aliases-package: com.example.demo.mybatis.entity
